version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobbackend
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./secrets:/app/secrets:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production